# Generated by Django 3.1.3 on 2020-11-23 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 23, 15, 1, 49, 60867)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology')], default='TECH', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
